lib/model/blob/AzuriteRequest.js

Java Azure SDK sends the `x-ms-lease-action` value in the uppercase, so it have to be transformed into lowercase.

The lease action should be case insensitive.

---

lib/xml/Serializers.js

Changes to deal with cases where expiry or start times are not defined.
Script to test changes can be found in issue #12 
Need to validate what happens in the real case if we submit XML without required fields to create an access policy using a tool like postman.

Address issue **PANIC** while creating storage container policy #12

---

README.md

Not sure if this is appropriate but it looks like the issues are all on the new site now.

Correct readme references to the repo to the new location

---

lib/core/table/TableStorageManager.js
lib/model/table/EntityGenerator.js

When the raw entity does not have a partition key or row key use the ones from the request params.
The C# azure storage sdk does not necessarily send the partition key and row key in the raw entity. Azure Storage apparently does not read it from the raw entity because code that works on it does not work on Azurite without these changes.

Entity generator now accepts optional partition and row key

---

lib/actions/table/QueryEntities.js
lib/model/table/AzuriteTableRequest.js

When using this with azure-storage-node and calling the api with retrieveEntity the wrong format is returned, it handles the response as it does when querying several entities
Return value when requesting one entity from dev
```json
{
"value": {
"_": [{
"Timestamp": "2018-06-08T10:09:31.010Z",
"Timestamp@odata.type": "Edm.DateTime",
"type": 1,
"PartitionKey": "asdasd123",
"RowKey": "a6c09770-6a69-11e8-ac4a-ddbdcad9d221"
}]
},
".metadata": {
"metadata": "http://127.0.0.1:10002/devstoreaccount1/$metadata#revokelist",
"etag": "W/\"fe-/JfNhqfuZdZakFgYTVFcUMDIGdc\""
}
}
```
Return value when requesting one entity from azure table
```json
{
"PartitionKey": {
"$": "Edm.String",
"_": "asdasd"
},
"RowKey": {
"$": "Edm.String",
"_": "839408a0-6a68-11e8-a3a3-fd722a41ad6b"
},
"Timestamp": {
"$": …
```

Fixed result when requesting single entity with rowkey and partitionkey

---

lib/middleware/blob/cors.js

Without this fix, azurite would fail because it was trying to call
```request.httpProps[N.ACCESS_CONTROL_REQUEST_HEADERS].toLowerCase()```
which will result in trying to call undefined.toLowerCase() if the preflight
request doesn't specify access-control-request-headers.
In addition, when validating a request against the CORS, the request would
fail to be validated if access-control-request-headers was empty.

Fix an issue with CORS when a preflight request has an empty headers list

---

lib/core/blob/StorageManager.js

Before this change, the Azure Java SDK was failing on the list operation if it included copied blobs:
```
Exception in thread "main" java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
[...]
Caused by: com.microsoft.azure.storage.StorageException: OK
at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:209)
at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:109)
... 4 more
Caused by: java.lang.NumberFormatException: For input string: "undefined"
at …
```

Always set the copyProgress field.

---

Dockerfile

Use explicit version tag 10.6-alpine instead of alpine to ensure a known
version is used. Copy package-lock.json before npm install to ensure
known dependencies are installed.

Dockerfile: deterministic builds

---

lib/core/AzuriteError.js
lib/core/HttpHeaderNames.js
lib/model/blob/AzuriteErrorResponse.js
lib/model/blob/AzuriteResponse.js

Introduces a new AzuriteErrorRespone, subclassed from AzuriteResponse, that can correctly package and send errors back to the client.
Also sets the x-ms-error-code header and adjusts the API version accordingly to improve compatibility with newer clients.
Finally, the AzuriteResponse class gains a send method, which will apply all headers, set status code, calculate content-length and send the data over the wire via an express `res` object. Over time, all Azurite actions can migrate to use this pattern, instead of manually applying all properties from the AzuriteResponse.

Refactored error handling

---

lib/core/AzuriteError.js
lib/middleware/table/actions.js
lib/middleware/table/validation.js
test/01_Basic_table_Tests.js

Send an error response when we catch an AzuriteError

---

lib/AzuriteTable.js
lib/actions/table/InsertEntity.js
lib/actions/table/UpdateEntity.js
lib/core/utils.js
lib/model/table/EntityGenerator.js
lib/model/table/EntityProxy.js
lib/validation/table/EntityIfMatch.js
test/01_Basic_table_Tests.js

Picks up changes from @michaelkruglos, but extends those in the following way:
* Disable express' etag generation
* Update entity operations to emit etag according to spec
* Update `EntityIfMatch` to match timestamp instead of etag
* Add tests
* Fixes #95

Update etag generation and matching in Table Service

---

lib/actions/table/QueryEntities.js

Appears to be from commit 9413bd7af4da7ffe24457180541ad1c6d2da8d10 for the 2.6.7 release, special behavior was introduced for single results. This breaks some clients as they are not expecting a structural change in the resulting payload, which appears to be inconsistent with the Microsoft official one.
I cannot find out exactly why this change was made as the history doesn't appear to be traceable beyond this, but I appreciate there might be a legitimate reason for this.
May be connected to #31.
I have a specific fake 5 F# test example I have attached below which will no longer explode after the change:
```
open System
open Microsoft.WindowsAzure.Storage
#load "./.fake/T1.fsx/intellisense.fsx"
#r "paket:
nuget FSharp.Azure.Storage //"
open FSharp.Azure.Storage.Table
type Thing = { …
```

Fix query single item incorrect behavior

---

package-lock.json
src/blob/errors/StorageError.ts
src/blob/errors/StorageErrorFactory.ts
src/blob/generated/utils/serializer.ts
src/blob/handlers/ContainerHandler.ts
src/blob/persistence/IBlobDataStore.ts
tests/blob/apis/container.test.ts
tests/testutils.ts

New Implemented APIs: 
•	ContainerHandler.acquireLease()
•	ContainerHandler.releaseLease()
•	ContainerHandler.renewLease()
•	ContainerHandler.breakLease()
•	ContainerHandler.changeLease()
Updated APIs:
•	ContainerHandler.Delete()
o	It will be blocked on a container which is in lease blocked status
•	ContainerHandler. getProperties()
o	Will return the correct lease status.
API pending update:
•	For all other API that will return container properties, like list container, need update the lease status. 
o	@XiaoningLiu , I have added a function to update the lease status of a container: ContainerHandler.updateLeaseAttributes(). As we talked, you will add it to related APIs.
Test:
•	Added all lease cases (5) from https://github.com/Azure/azure-storage-js/blob/master/blob/tests/containerurl.test …

Add container lease feature

---

src/blob/errors/StorageErrorFactory.ts
src/blob/handlers/AppendBlobHandler.ts
src/blob/handlers/BlobHandler.ts
src/blob/handlers/BlockBlobHandler.ts
src/blob/handlers/ContainerHandler.ts
src/blob/handlers/PageBlobHandler.ts
src/blob/handlers/ServiceHandler.ts
src/blob/persistence/IBlobDataStore.ts
tests/blob/apis/blob.test.ts
tests/blob/apis/container.test.ts

Please note, it’s still not well tested (only unit test pass), so the PR is only for code review. 
**Please don’t merge.**
I will continue test and refine it.
New Implemented APIs: 
•	BlobHandler.acquireLease()
•	BlobHandler.releaseLease()
•	BlobHandler.renewLease()
•	BlobHandler.breakLease()
•	BlobHandler.changeLease()
Updated APIs:
•	BlobHandler. getProperties()
o	Will return the correct lease status.
•	Per the doc, we need to check lease ID (and set lease state to available on lease expired blob), when write blob. Related Blob APIs:
o	(Updated)Has add code to do lease check and lease status change:
	SetBlobMetadata (BlobHandler.setMetadata)
	DeleteBlob(BlobHandler,delete)
	PutBlockList (BlockBlobHandler.commitBlockList)
	PutPage(uploadPages)
o	(Add comment)Add comments TODO the …

Implement Blob Lease

---

src/blob/handlers/BlobHandler.ts
src/blob/handlers/ContainerHandler.ts
src/blob/persistence/IBlobDataStore.ts
src/blob/persistence/LokiBlobDataStore.ts
tests/blob/apis/blob.test.ts
tests/blob/apis/container.test.ts

Snapshot API has been implemented, and the DB schema updated.
#190 
There are now issues with the correctness of several APIs and tests which need to be corrected to account for snapshots in the blob collection.
1. collection indices extended by snapshot property.
1. listBlobs API on persitent storage extended to account for snapshots
1. All special naming tests now failing
1. Correctness of list blob tests needs to be checked.
Number of expected results no longer correct on flat and hierarchy tests.
1. Correctness of delete / undelete operations 
BlobDeleteMethodOptionalParams.deleteSnapshots
Required if the blob has associated snapshots. Specify one of the following two options:
include: Delete the base blob and all of its snapshots. 
only: Delete only the blob's snapshots and not the …

Snapshot implementation for #190

---

Dockerfile

Module vscode was not being installed when building Docker image - running `npm config set unsafe-perm=true` before install allows this module to be installed within the container correctly.

Run install as root in docker so that vscode module installs correctly

---

lib/routes/table/EntityRoute.js
lib/routes/table/TableRoute.js

While debugging, I noticed that some table operations were being incorrectly handled by both the `TableRoute` and `EntityRoute` handlers. For example, I encountered problems deleting tables using Azure Storage Explorer.
```
DELETE /Tables('Example')
```
On the first pass, the `TableRoute` handler correctly parsed the request as a `DELETE_TABLE` operation with a `AzuriteTableRequest.tableName` equal to "Example". However, the call to express's `next()` caused the request to flow to `EntityRoute`. On this second pass, the `EntityRoute` handler incorrectly parsed the request as a `DELETE_ENTITY` operation with a `AzuriteTableRequest.tableName` equal to "Tables". It was this second, incorrect request that was actually processed and resulted in an error (because a table named "Tables" didn't …

Fixes incorrect handling of table management URLs

---

src/blob/handlers/ContainerHandler.ts
src/blob/persistence/IBlobDataStore.ts
src/blob/persistence/LokiBlobDataStore.ts
src/blob/persistence/LokiReferredExtentsAsyncIterator.ts
tests/blob/apis/container.test.ts

In the Azure docs for List Blobs it specifies
> Blobs are listed in alphabetical order in the response body, with upper-case letters listed first.
(via: https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs search for "alphabetical")
However we have found that Azurite does not guarantee that ordering when listing blobs with a `prefix` option. This PR simply adds a test that exposes that behavior and adds a lokijs `simplesort` call to the `listBlobs` function.
We found this bug by trying to use Azurite for testing when implementing a client app for Azure Blob storage. When we went to write paging using the `Marker` functionality we noticed that when the prefix option is sent to Azurite the results are returned in reverse create order, not alphabetical order. When tested …

Fix listblobs order when filtering by prefix

---

.dockerignore
.gitattributes
CONTRIBUTION.md
Dockerfile
README.md

Add .gitattributes to assist people using different host operating systems. Add .dockerignore to minimise the amount of files sent to docker machine when creating the docker image. Replaced "npm install" with "npm ci" in various places, in particular in Dockerfile to make container image builds repeatable.
=> intended to go to branch "dev"
=> Can't think of reasonable automated tests
=> Done

Add .gitattributes and .dockerignore; replace "npm install" with "npm ci"

---

src/blob/errors/StorageErrorFactory.ts
src/blob/handlers/PageBlobHandler.ts
src/blob/persistence/LokiBlobMetadataStore.ts
src/blob/persistence/SqlBlobMetadataStore.ts
tests/blob/apis/blockblob.test.ts
tests/blob/apis/pageblob.test.ts

Fix following 3 issues:
https://github.com/Azure/Azurite/issues/400: Check if block blob exists should fail if blocks are all uncommitted
https://github.com/Azure/Azurite/issues/401: Uploading blocks with different lengths of IDs to the same blob should fail
https://github.com/Azure/Azurite/issues/410: Real server compatibility: x-ms-blob-sequence-number of 0 should be returned for HEAD requests on Page blob

Fix 3 blob issues

---

src/blob/handlers/BlobHandler.ts
src/blob/middlewares/blobStorageContext.middleware.ts
src/common/utils/constants.ts
src/queue/middlewares/queueStorageContext.middleware.ts
tests/blob/specialnaming.test.ts

Solves #403 - adds ability to use production-style URLs when using "account.localhost" as the host name.
E.g. default URL format for emulator is
> http://hostname[:port]/account/container
this adds ability to use 
> http[s]://account.localhost[:port]/container
It's users' responsibility that account.localhost resolves to 127.0.0.1. On Windows (I believe this works out of the box on Linux), this can be achieved by adding hosts file record, for example. 
C:\Windows\System32\drivers\etc\hosts
```
<...>
127.0.0.1       devstoreaccount1.localhost
```
I contemplated putting this functionality under some sort of flag (like environmental variable).
But then I realized that it's very unlikely to break any existing use patterns, as it requires issuing API requests to accountname.localhost, and …

Support production-style URLs (e.g. http://account.localhost/container)

---

src/blob/handlers/ContainerHandler.ts
src/blob/persistence/BlobReferredExtentsAsyncIterator.ts
src/blob/persistence/IBlobMetadataStore.ts
src/blob/persistence/LokiBlobMetadataStore.ts
src/blob/persistence/SqlBlobMetadataStore.ts
tests/blob/apis/container.test.ts

Fixes https://github.com/Azure/Azurite/issues/463
Currently, `listBlobs` will return all blobs, including staged / uncommitted blobs.  This is a discrepancy from real Azure storage, where only committed blobs are returned unless you explicitly request them using the `includes: uncommittedblobs` option.

listBlobs should only list committed blobs

---

.gitignore
src/table/errors/StorageErrorFactory.ts
src/table/handlers/TableHandler.ts
src/table/persistence/ITableMetadataStore.ts
src/table/persistence/LokiTableMetadataStore.ts
tests/table/apis/table.test.ts

PR for #485 
Delete Table & Tests Implemented.

DeleteTable Implementation

---

src/common/utils/utils.ts
tests/blob/utils.test.ts

Recently, I have run into a problem using the official Golang SDK for Azure Blob Storage and the Azurite emulator.
I have previously discussed the issue over at the SDK's repo (see https://github.com/Azure/azure-storage-blob-go/issues/191).
The production service handles metadata operations slightly differently than the service emulator, as it accepts set-metadata operations using a canonicalized header prefix (`X-Ms-Meta-` instead of the documented `x-ms-meta-`).
I guess it's best to stick closer to the production service than to the literal documentation in this case. I've updated the respective part of Azurite's metadata header algorithm to accept the same headers that the production service accepts.

Allow canonicalized prefix for blob metadata operations

---

.dockerignore
Dockerfile

This contains a new Dockerfile which allows creating much smaller Docker images and with less layers.
It uses multi-stage builds, so tsc runs in a different container (bonus: it now runs "npm run test" too).
Also, updated .dockerignore that was preventing the container from copying the self-signed cert used by tests

New, leaner Dockerfile

---

package-lock.json
package.json

upgrade `sequelize` dependency to `6.3.0`. this includes https://github.com/sequelize/sequelize/pull/12459 which fixes issues with the `mssql` dialect https://github.com/sequelize/sequelize/issues/11902 and https://github.com/sequelize/sequelize/issues/11684. 
Closes #467

Upgrade sequelize to 6.3.0 

---

src/table/handlers/TableHandler.ts
src/table/persistence/ITableMetadataStore.ts
src/table/persistence/LokiTableMetadataStore.ts
tests/table/apis/table.entity.test.ts
tests/table/apis/table.test.ts

[Table] Phase 1 Feature - Insert Or Replace Entity #492
Upsert added incl query table entities with partition key and row key in the loki data handler.
Added test case to validate "insert" API call via SDK, and verified that this does not include the ifMatch / etag header on the request to the API.

[Table] Phase 1 Feature - Insert Or Replace Entity

---

src/blob/persistence/SqlBlobMetadataStore.ts
tests/blob/apis/blockblob.test.ts

currently there is an issue with the `sql` metadata store and `getBlockList`. this API behaves differently between `loki` and `sql`, and the `loki` behavior appears to be correct when compared to real azure storage.
a test has been added to illustrate the issue, and a secondary commit will be added to validate the fix.
fixes https://github.com/Azure/Azurite/issues/579

fix sql metadata store getBlockList for non-existent blob

---

src/blob/persistence/SqlBlobMetadataStore.ts
tests/blob/sas.test.ts

this adds missing functionality to the sql metadata store to enable asynchronous blob copy operations. it has full parity with the `loki` store, so the tests have been enabled for both `@loki @sql` where appropriate.
fixes https://github.com/Azure/Azurite/issues/443.

enable async copy for sql metadata store

---

src/table/TableRequestListenerFactory.ts
src/table/TableServer.ts
src/table/errors/StorageErrorFactory.ts
src/table/middleware/tableStorageContext.middleware.ts
src/table/utils/constants.ts
src/table/utils/utils.ts
tests/table/apis/table.test.ts

Fixes #516. The implementation is 90% copy/paste from the equivalent methods in blob storage.

Add API Version check for table storage middleware

---

ChangeLog.md
src/azurite.ts
src/blob/main.ts
src/queue/main.ts

Docker defaults to using SIGTERM on `docker stop` This consolidates the handlers to a single function used by the 3 ways of stopping the app.
You can see this by the time it takes to stop the Azurite container without handling `SIGTERM` vs when you handle it. Docker will wait 10 seconds before forcibly killing the container. 
```
❯ time docker stop azurite
azurite
real    0m10.467s
user    0m0.073s
sys     0m0.100s
```
```
❯ time docker stop azurite-sigterm
azurite-sigterm
real    0m0.431s
user    0m0.111s
sys     0m0.053s
```

Handle SIGTERM. Signal for Docker stop

---

.gitattributes

This adds a `.gitattributes` file as it appears in the `master` branch. By checking out with LF line endings, when later packed the NPM package will contain LF line endings as `bash` requires in order to parse `#!` first lines of text files.
Fixes #110
Fixes #112

Use LF line endings

---

ChangeLog.md
src/blob/generated/artifacts/mappers.ts
src/blob/generated/artifacts/models.ts
src/blob/handlers/ContainerHandler.ts
src/blob/persistence/LokiBlobMetadataStore.ts
src/blob/persistence/SqlBlobMetadataStore.ts
swagger/blob-storage-2019-02-02.json
swagger/blob.md
tests/blob/apis/container.test.ts

Azure includes \<Snapshot\> XML tag in output only if it is not empty.
Such behaviour is documented in
https://docs.microsoft.com/en-us/rest/api/storageservices/enumerating-blob-resources
Azure SDK for Go fails while parsing response with empty tag.
Fixes #663

Do not return empty <Snapshot/> tag in container blobs enumeration.

---

ChangeLog.md
package-lock.json
package.json
src/blob/BlobRequestListenerFactory.ts
src/blob/handlers/AppendBlobHandler.ts
src/blob/handlers/BaseHandler.ts
src/blob/handlers/BlobHandler.ts
src/blob/handlers/PageBlobHandler.ts
tests/blob/handlers/AppendBlobHandler.test.ts

Due to a bug in azure-sdk-for-go, the Append Block API call fails because this legacy library always sends a non-zero Content-Length header. This fix relaxes this Content-Length check when the `--loose` flag is set.
Also adds a bunch of tests for AppendBlobHandler. Hope you don't mind having `ts-mockito` as a dependency. Testing this functionality without mocking the metadatastore and the extentstore doesn't look feasible.
Fixes #682.

Skip Content-Length check for Append Block if --loose is set

---

src/common/utils/utils.ts
src/table/handlers/TableHandler.ts
tests/table/apis/table.entity.test.ts

Fix for https://github.com/Azure/Azurite/issues/688 (format of etag returned by Table Storage endpoint)

Etag returned by Table Storage follows Azure format now

---

ChangeLog.md
src/common/utils/utils.ts
tests/table/apis/table.entity.test.ts

The PR is to fix : https://github.com/Azure/Azurite/issues/743

Fix table etag format to be aligned with server, by escape encode ':' in it

---

ChangeLog.md
src/table/batch/TableBatchOrchestrator.ts
src/table/batch/TableBatchSerialization.ts
tests/table/apis/table.entity.test.ts

Addresses the case where RowKey or PartitionKey are complex, and incorrectly deserialized by Batch API.
2 Test Cases added for complex RowKey and PartitionKey
Based on my testing the following issues should be resolved:
fixes #741  
fixes #745  
fixes #733  
fixes #750

Update to Table Batch API to address complex row and partition keys

---

src/table/batch/TableBatchOrchestrator.ts
src/table/batch/TableBatchSerialization.ts
tests/table/apis/AzureDataTablesTestEntity.ts
tests/table/apis/TestEntity.ts
tests/table/apis/table-batch-api-error-handling.md
tests/table/apis/table.batch.tests.errorhandling.ts
tests/table/apis/table.entity.test.utils.ts
tests/table/apis/table.entity.tests.azure.data-tables.ts
tests/table/apis/table.entity.tests.ts
tests/table/apis/table.test.ts

Fixes #739 
Now correctly serializes errors from Table API, adding support for @azure/data-tables SDK.  
Does not yet observe atomicity and snapshots on table API transactions.  
See tests\table\apis\table-batch-api-error-handling.md for error handling specs implemented so far and those still outstanding.

Table batch error handling

---

src/table/persistence/LokiTableMetadataStore.ts
tests/table/apis/AzureDataTablesTestEntity.ts
tests/table/apis/table.entity.tests.azure.data-tables.ts

added inverted commas to query filter when applied to metadata layer for Long int, as these are stored as string in LokiJs, as opposed to ints, which are stored as number.
Added 2 tests via the @azure/data-tables tests for int and long int.
Fixes #755

Corrects query for Long Int in Metadata layer

---

ChangeLog.md
src/table/handlers/TableHandler.ts
tests/table/apis/table.entity.tests.ts

Allows Insert with empty string on partitionKey and rowKey.
Fixes #834

Allows Insert with empty string on partitionKey and rowKey

---

azure-pipelines.yml

16.04 LTS environment is deprecated and will be removed on September 20, 2021.
Migrate to ubuntu-latest

Update ubuntu to use latest rather than 16.04 in Pipeline

---

ChangeLog.md
src/blob/errors/StorageErrorFactory.ts
src/blob/handlers/BlobHandler.ts
src/blob/persistence/LokiBlobMetadataStore.ts
tests/blob/apis/blob.test.ts

Fixes #603 
This makes the syncCopyFromURL operation for blobs return a copy status (`x-ms-copy-status` response header).
The value of the header can only be "success" as defined in the `SyncCopyStatusType` enum. However all methods from the metadata stores seem to return `BlobProperties`, which contain a normal `CopyStatusType`.
I added a conversion to the sync copy status to the `BlobHandler` as well as a new error in case the copy status is not "success". Please let me know if this is the correct approach here. Otherwise I'm happy to change that.

Return x-ms-copy-status from syncCopyFromURL

---

ChangeLog.md
src/table/persistence/LokiTableMetadataStore.ts
tests/table/apis/table.entity.tests.azure.data-tables.ts

fixes #970 
Fixes an issue in the tokenization of queries which contain numbers and no spaces between number and parens in the query filter.
This occurs due to differences in some SDKs.
Added test to cover this change and test the behavior using differently formatted query strings.

Corrected tokenization of queries in table storage

---

ChangeLog.md
src/blob/handlers/BlobHandler.ts
src/blob/middlewares/StrictModelMiddlewareFactory.ts
tests/blob/sas.test.ts

Support rscc, rscd, rsce, rscl, rsct query parameters in SAS tokens; fixes https://github.com/Azure/Azurite/issues/997.

Support rscc, rscd, rsce, rscl, rsct query parameters in SAS tokens

---

ChangeLog.md
src/table/persistence/LokiTableMetadataStore.ts
tests/table/apis/table.entity.tests.azure.data-tables.ts

fixes #1051
Contains test case to validate change.
Corrects case for query conversion in metadata store if no space between Boolean value and parens.

Fixes issue with incorrect results when using Boolean values in table query

---

azure-pipelines.yml

Updating the pipeline as we are getting failed PRs.
I suspect that we need to pre-empt the deprecation of macOS-10.14 images, as these are not being found:
```
##[warning]An image label with the label macOS-10.14 does not exist.\
,##[error]The remote provider was unable to process the request.
```
I assume that we will eventually need to change to macOS-11
See:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

Updated azure-pipeline.yaml MacOS VM Image name

---

ChangeLog.md
azure-pipelines.yml

Hey, hope this type of PR is ok. I noticed a lot of CI jobs failing due to a brownout of the current windows image being used (see below snippet for full error). I've updated the pipelines to use the latest version of windows available for Azure CI in order to fix this
This PR: 
- Updates Azure pipelines to use the latest windows image (`windows-2022`) due to deprecation of `vs2017-win2016` (EOL is March 2022). 
Documentation / references:
https://github.com/actions/virtual-environments/issues/4312
https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation
Error in CI:
```
##[error]This is a scheduled windows-2016 brownout. The windows-2016 environment is deprecated and will be removed on March 15, 2022. For more details, see …
```

ci - fix windows CI deprecation

---

ChangeLog.md
package.json
src/common/utils/utils.ts
src/table/handlers/TableHandler.ts
src/table/persistence/LokiTableMetadataStore.ts
src/table/utils/utils.ts
tests/table/apis/table.entity.test.utils.ts
tests/table/apis/table.entity.tests.issues.ts

Fix https://github.com/Azure/Azurite/issues/1229
This is pretty low priority, but I wanted to start with an easy bug fix as I ramp up on this repository. This is only my 3rd PR 😄.

Allow any weak etag even if it doesn't match the pattern (412 should happen)

---

ChangeLog.md
src/table/persistence/LokiTableMetadataStore.ts
tests/table/apis/table.entity.issues.test.ts

This fix an issue when loading multiple pages of rows that does have empty string rowkey.  #1554

Fixed load multiple page with rows without rowkey

---

ChangeLog.md
src/table/batch/TableBatchOrchestrator.ts
src/table/persistence/LokiTableMetadataStore.ts
tests/table/apis/table.entity.test.ts
tests/table/auth/sas.test.ts

If-Match: * and no If-Match header behaves differently. If-Match: * requires the entity to exist.
Address https://github.com/Azure/Azurite/issues/1565 as well as another pre-existing problem where Batch Update acted like an Upsert.

Fix upsert merge to not throw a 404 when the entity is missing

---

package.json

Add support for building docker images for amd64 and arm64 architectures.
Addresses [issue](https://github.com/Azure/Azurite/issues/1556)
@kdambekalns
@blueww 
When running on Apple Silicon without multi-arch support
When running on Apple Silicon with multi-arch support
The scripts need to be invoked during your CI/CD build pipeline.
It looks like that partially occurs in `azure-pipelines.yml` however I couldn't find anything that actually publishes to the docker image/container registry.
Ideally the order would go something like this:
```
npm run docker:init-multi-platform-builder
npm run docker:build-amd64
npm run docker:build-arm64
npm run docker:publish-amd64
npm run docker:publish-arm64
npm run docker:create-manifest-versioned
npm run docker:create-manifest-latest
npm run …
```

feat: add scripts for building multi-architecture azurite docker images

---

src/table/handlers/TableHandler.ts
tests/table/apis/table.entity.rest.test.ts

Fix issue: [#1579](https://github.com/Azure/Azurite/issues/1579)
Added test case to check specifically for etag in headers in table.entity.rest.test.ts
and modified TableHandler.ts in line 686 to solve issue.
This is an updated PR of (closed) #1613 since the old PR contained unwanted changes.

Fix issue 1579: Missing etag in header for GET Operation

---

ChangeLog.md
src/extension.ts

Fixes https://github.com/microsoft/vscode-azurestorage/issues/1000
We're have an issue where the emulator hasn't actually started by the time we refresh the tree. I'm guessing that this is because the registered start commands aren't actually `async` so when we try to `await` it, it doesn't actually wait for it to resolve.

Make emulator start commands asynchronous

---

azure-pipelines.yml

This is because pipeline report error: 
> ##[error]This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on September 30th, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5583
> ,##[error]The remote provider was unable to process the request.
Per https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software:
- upgrade "macOS-10.15" to "macOS-latest"
- Also change "windows-2022" to "windows-latest", they point to same image currently
Make sure test cases are added to …

Upgrade mac version in pipeline

---

src/blob/handlers/ContainerHandler.ts

Regarding the [list-blobs](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs#uri-parameters) endpoint. Azure handles an empty `delimiter` query parameter as such (as if it was not given). But Azurite defaults it to a `/` (slash). This behaviour was [added by](https://github.com/Azure/Azurite/commit/6ef53aec1c3c32be8754237a08e5c6ab9990cbb0#diff-ef140eda9dd541760b3a8c2ad07ee5462eb8b1a6f87ea7669107623fa5fcfb77R829) @XiaoningLiu, but I cannot determine the exact reason. 
It causes incompatibility issues. E.g. in the Azure Storage Explorer; the returned flat list of blobs is empty when there are in fact blobs in the container. And also in minio, which [uses the azure storage go library](https://github.com/minio/minio/blob/RELEASE.2022-03-17T06-34-49Z/cmd/gateway/azure/gatewa …

don't default the delimiter for list blob hierarchy to slash

---

ChangeLog.md
src/blob/handlers/AppendBlobHandler.ts

Add missing requestId to the appendBlock operation of an append blob.
Fixes #631.

Add requestId to appendBlock operation.

---

ChangeLog.md
src/table/persistence/QueryInterpreter/QueryNodes/DateTimeNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/EqualsNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/GreaterThanEqualNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/GreaterThanNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/GuidNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/LessThanEqualNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/LessThanNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/NotEqualsNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/ValueNode.ts
src/table/persistence/QueryInterpreter/QueryParser.ts
tests/table/unit/query.interpreter.unit.test.ts

This PR makes some changes to the way our query interpreter is architected, enabling us to handle `DateTime` comparisons with more appropriate custom logic which avoids the `myField eq datetime'2023-07-27T14:01:00.000000Z'` query failing to match backend entries with the same underlying format due to the manner in which JavaScript's `Date` constructor truncates these values.
Fixes #2069

fix: Resolve issues with datetime comparisons in scenarios where microsecond precision is provided in the underlying value.

---

ChangeLog.md
src/blob/authentication/AccountSASAuthenticator.ts
src/blob/authentication/BlobSASAuthenticator.ts
src/queue/authentication/QueueSASAuthenticator.ts
src/table/authentication/AccountSASAuthenticator.ts
src/table/authentication/TableSASAuthenticator.ts
tests/blob/sas.test.ts

This PR fixes use cases below when using `AZURITE_ACCOUNTS` defining a second key for the account.
- A blob request using any key but any of the 2 keys defined in `AZURITE_ACCOUNTS` passes instead of failing.
- A blob request using the second key defined in `AZURITE_ACCOUNTS` fails instead of passing.

Fix validation of Blob SAS token when using the second key for an account in `AZURITE_ACCOUNTS`

---

ChangeLog.md
src/table/persistence/QueryInterpreter/QueryNodes/BinaryDataNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/DateTimeNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/GuidNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/NotEqualsNode.ts
src/table/persistence/QueryInterpreter/QueryNodes/ValueNode.ts
tests/table/apis/table.entity.query.test.ts
tests/table/unit/query.interpreter.unit.test.ts

This PR fixes the issues raised in #2169 which pertain to the comparison between empty (and by extension, null and missing) properties and GUIDs. This issue was reproduced with the included test suite additions, and fixed by handling the `null`/`undefined`/empty case explicitly for GUID comparisons.

fix(table): Ensure that we correctly handle value comparisons against null/empty/undefined values for GUIDs and DateTimes

---

ChangeLog.md
src/blob/middlewares/blobStorageContext.middleware.ts
src/queue/middlewares/queueStorageContext.middleware.ts
src/table/middleware/tableStorageContext.middleware.ts
tests/blob/specialnaming.test.ts
tests/queue/queueSpecialnaming.test.ts
tests/table/apis/table.validation.rest.test.ts
tests/table/utils/table.entity.tests.rest.submitter.ts
tests/table/utils/table.entity.tests.utils.for.rest.ts

This PR adds additional validation to authentication path computation for secondary requests.

Fixes issue #2208

---

ChangeLog.md
src/table/authentication/ITableSASSignatureValues.ts
tests/table/auth/sas.test.ts

Fix #1359 
According to [link](https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#:~:text=Table%20names%20must%20be%20lowercase.), Table names must be lowercase in canonicalizedResource in the stringToSign of SAS.

fix 1359: table sas failure with upper case table name

---

ChangeLog.md
src/blob/handlers/BlobBatchHandler.ts

If a SubmitBatch request has a HTTP header that has a HTTP header
delimiter (":") in its value, the SubmitBatch request is failed as
"400 One of the request inputs is not valid."
For example, if `user-agent` header is `azsdk-cpp-storage-blobs/12.10.0-beta.1 (Darwin 23.1.0 arm64 Darwin Kernel Version 23.1.0: Mon Oct 9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103)`, all `SubmitBatch()` requests are failed.

Fix HTTP header parsing in SubmitBatch request

---

ChangeLog.md
src/blob/handlers/BlobHandler.ts
tests/blob/apis/blockblob.test.ts
tests/blob/sas.test.ts

Fix issue of copy succeeded without 'r' permission in SAS token credential

---

ChangeLog.md
src/table/entity/EdmDouble.ts
tests/table/apis/table.entity.test.ts

Fix : https://github.com/Azure/Azurite/issues/2387

Fail the insert entity request with double property whose value is greater than MAX_VALUE (Issue #2387)

---

package-lock.json
package.json

This PR bumps the [tedious](https://www.npmjs.com/package/tedious) version from 16.0.0 to 16.7.0. Version 16.0.0 introduces a [vulnerability](https://cwe.mitre.org/data/definitions/1333.html) which is fixed in 16.7.0.

Bump tedious from 16.0.0 to 16.7.0

---

ChangeLog.md
src/table/persistence/QueryInterpreter/QueryNodes/BigNumberNode.ts
src/table/persistence/QueryInterpreter/QueryParser.ts
tests/table/apis/table.entity.query.test.ts
tests/table/unit/query.parser.unit.test.ts
tsconfig.json

Fix issue of returning incorrect entities when querying table with int64 values

---

ChangeLog.md
src/blob/persistence/LokiBlobMetadataStore.ts
src/blob/persistence/SqlBlobMetadataStore.ts
tests/blob/apis/appendblob.test.ts
tests/blob/apis/blockblob.test.ts

Fix issue of not refreshing lease state within blockBlob.upload operation.

---

ChangeLog.md
README.md
package-lock.json
package.json
src/blob/utils/constants.ts
src/queue/utils/constants.ts
src/table/utils/constants.ts

Bump API version to 2024-08-04

---

ChangeLog.md
src/blob/errors/StorageErrorFactory.ts
src/blob/handlers/BlobHandler.ts
tests/blob/apis/appendblob.test.ts
tests/blob/apis/blockblob.test.ts
tests/blob/apis/pageblob.test.ts

Fix 2 issues of download blob range:
#2410: Download rang > 0 from 0 size blob should report error
#2409: Download blob range only return ContentMD5 when request has header `x-ms-range-get-content-md5`

Fix 2410/2409: fix issue of download blob range.

---

ChangeLog.md
package-lock.json
package.json

[Issue #2415] Bump mysql2 version

---

ChangeLog.md
src/common/persistence/FSExtentStore.ts
tests/blob/fsStore.test.ts

Fixes #1346
The underlying file, where the data is saved was closed if any error occurred while reading from the client connection. Subsequently, the file was attempted to be used again, but it is closed.

Fixed an issue where premature client disconnections led to all following requests failing with a 500 error #1346

---

.github/workflows/PrValidation.yml

The Azure ADO pipeline will be deleted on 8/20, so move it to github action. 
TODO: The "Azurite_Governance_Origin" task not converted, since not find same github action
Also deprecated node 14 since it's not in nodejs LTS matrix, and add node 22 in PR check.
https://github.com/Azure/Azurite/issues/2441
Before: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/weiwei/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/weiwei/AppData/Local/Temp/msohtmlclip1/01/clip_file …

[Test] move PR validation pipeline to github action

---

ChangeLog.md
src/common/persistence/FSExtentStore.ts
tests/blob/fsStore.test.ts

On Windows to truncate the file, which is opened in append mode, the file first needs to be closed. Expanded the test case to include another valid extent, this time prior to failed update.
This addresses the [comment](https://github.com/Azure/Azurite/pull/2433#issuecomment-2262591113) in #2433.

Fixed failing test on Windows caused by #2433

---

ChangeLog.md
src/blob/handlers/AppendBlobHandler.ts
src/blob/handlers/BlobHandler.ts
src/blob/handlers/BlockBlobHandler.ts
src/blob/handlers/ContainerHandler.ts
src/blob/handlers/PageBlobHandler.ts
src/common/utils/constants.ts
src/common/utils/utils.ts
tests/blob/apis/appendblob.test.ts
tests/blob/apis/blob.test.ts
tests/blob/apis/blockblob.test.ts
tests/blob/apis/container.test.ts
tests/blob/apis/pageblob.test.ts

Fixes #2451 
This PR also follows the [suggestion](https://github.com/Azure/Azurite/issues/2451#issuecomment-2301483686) to fix all the blob APIs, not just putBlob.
To make sure this is always checked, we check for valid metadata names in the conversion function instead of in each API individually.

Prevents invalid metadata names in Blob APIs

---

tests/queue/apis/messageid.test.ts

Fix the test case failed like https://github.com/Azure/Azurite/actions/runs/11097981740/job/30830329538?pr=2428
>   1) MessageId APIs test
>        update and delete message with all parameters @loki:
>      FetchError: request to http://127.0.0.1:11001/devstoreaccount1/queue172766217678200480/messages?peekonly=true&timeout=30 failed, reason: socket hang up
>       at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)
>       at ClientRequest.emit (node:events:519:28)
>       at ClientRequest.emit (node:domain:488:12)
>       at emitErrorEvent (node:_http_client:103:11)
>       at Socket.socketOnEnd (node:_http_client:530:5)
>       at Socket.emit (node:events:531:35)
>       at Socket.emit (node:domain:488:12)
>       at endReadableNT …

Queue test fix

---

package.json

Closes https://github.com/Azure/Azurite/issues/2467
Optionally this could additionally add `onStartupFinished` and that will at least minimise the performance impact of Azurite on vscode startup, however if you're going to do that, no point in having any of the other activation events and they should all be removed.
Potentially considered a breaking change because a "new" workspace won't activate the extension and people may be used to seeing the blob/table/etc. links in the bottom status tray and they won't show up until you run an azurite command. Once run however and the azurite files are present in the workspace, it will auto-start from then on for the project.

Activate only on command or Azurite file presence

---

.vscode/launch.json
README.md

Azurite Unit test style is "BDD" instead of "TDD", but launch.json use "TDD" . Althrough it works in before macha version, after upgrade mocha the manual test fail with "ReferenceError: describe is not defined", since macha can't recognize the test file.
See [BDD](https://mochajs.org/#bdd)
- The BDD interface provides describe(), context(), it(), specify(), before(), after(), beforeEach(), and afterEach().
- The TDD interface provides suite(), test(), suiteSetup(), suiteTeardown(), setup(), and teardown()
Add change log for the code change …

Fix manual test failure with mocha upgrade, and remove the build status link since the pipeline is removed.

---

ChangeLog.md
src/table/batch/TableBatchSerialization.ts
tests/table/go/main.go

Fix issue : https://github.com/Azure/Azurite/issues/2519
currently latest Go SDK will fail with "Unexpected EOF" when run table batch TransactionTypeInsertReplace or TransactionTypeAdd.  (TransactionTypeInsertMerge won't fail)
The root cause is : There are 3 "\r\n" after etag in responds from product Azure, but only 2 "\r\n" in the responds from Azurite.
**Responds from product Azure:**
```
358
--batchresponse_4d6c18c7-3a5f-4e71-96be-5ab90f68bf16
Content-Type: multipart/mixed; boundary=changesetresponse_d9a53c97-d6eb-4038-929f-6ffc409948e5
--changesetresponse_d9a53c97-d6eb-4038-929f-6ffc409948e5
Content-Type: application/http
Content-Transfer-Encoding: binary
HTTP/1.1 204 No Content
X-Content-Type-Options: nosniff
Cache-Control: no-cache
DataServiceVersion: 1.0;
ETag: …
```

Fixed `Unexpected EOF` error when batch InsertReplace table entities with Go SDK (issue #2519)

---

ChangeLog.md
src/blob/errors/NotImplementedError.ts
src/blob/persistence/SqlBlobMetadataStore.ts
src/queue/errors/NotImplementedError.ts

Per the suggestion of https://github.com/Azure/Azurite/issues/810#issuecomment-2545435163, change the responds status code for not implemented API from 500 to 501. (only change B/Q, since Table already use 501)
I have tested with .net SDK, after the change, .net SDK won't retry on the not implemented API and will fail faster.

Change the responds status code for not implemented API from 500 to 501 

---

ChangeLog.md
src/blob/errors/StorageErrorFactory.ts
src/blob/handlers/BlobHandler.ts
src/blob/utils/utils.ts
tests/blob/RequestPolicy/RangePolicyFactory.ts
tests/blob/apis/blob.test.ts
tests/blob/apis/blockblob.test.ts
tests/blob/apis/pageblob.test.ts

Fix #2458, based on #2461
I'm not sure how to provoke an invalid range header in the unit tests; @blueww can you give me a hint?

Ignore invalid range in blob download

---

ChangeLog.md
src/blob/persistence/QueryInterpreter/QueryParser.ts
tests/blob/unit/query.parser.unit.test.ts

Fix for the [issue #2514](https://github.com/Azure/Azurite/issues/2514)

Fix issue of filtering blobs with range conditions on tags

---

ChangeLog.md
src/table/persistence/LokiTableStoreQueryGenerator.ts
tests/table/apis/table.entity.issues.test.ts
tests/table/utils/table.entity.test.utils.ts

Fixed default table HealthCheck fails with 400 bad request
