lib/core/blob/StorageManager.js
This PR seems to fix the issue #3.
=> Incorrect blob type when fetching the copy status #3

README.md
Update to notify about new architecture.
=> New arch doc update

lib/core/utils.js, lib/model/table/EntityGenerator.js
=> Made etag handling same as in microsoft

.gitignore, .lintstagedrc, .vscode/launch.json, azure-pipelines.yml, package-lock.json, package.json, src/blob/BlobConfiguration.ts, src/blob/BlobRequestListenerFactory.ts, src/blob/BlobServer.ts, src/blob/generated/ExpressRequestAdapter.ts, src/blob/generated/IRequest.ts, src/blob/handlers/BlobHandler.ts, src/blob/handlers/BlockBlobHandler.ts, src/blob/handlers/ContainerHandler.ts, src/blob/handlers/IPageBlobRangesManager.ts, src/blob/handlers/PageBlobHandler.ts, src/blob/handlers/PageBlobRangesManager.ts, src/blob/handlers/ServiceHandler.ts, src/blob/main.ts, src/blob/persistence/IBlobDataStore.ts, src/blob/persistence/LokiBlobDataStore.ts, src/blob/utils/constants.ts, src/blob/utils/utils.ts, src/common/ServerBase.ts, src/common/ZeroBytesStream.ts, tests/blob/apis/pageblob.test.ts, tests/blob/blockblob.highlevel.test.ts, tests/blob/handlers/PageBlobRangesManager.test.ts, tests/blob/handlers/pageblob.handler.test.ts, tests/testutils.ts
* Caching file descriptors for performance improvement in persistence layer
* Improved ETag implementation; Clean up codes; Added start and close console output;
* Added tslint into azure pipeline checking; Added prettier before commit
* Create page ranges manager to manage all page ranges operations
* Added tons of test cases for page blob operations
* Updated persistencyID to IPersistencyChunk model to describe sub range of persitency extent
=> Newarch dev

README.md
It was very difficult for me to find this information, I had to dig through a lot of other Azure documentation to find it.
=> README now includes shared key credentials

package-lock.json, package.json, src/blob/BlobServer.ts, src/blob/gc/BlobGCManager.ts, src/blob/handlers/BlobHandler.ts, src/blob/handlers/BlockBlobHandler.ts, src/blob/handlers/ContainerHandler.ts, src/blob/persistence/IBlobDataStore.ts, src/blob/persistence/LokiAllExtentsAsyncIterator.ts, src/blob/persistence/LokiBlobDataStore.ts, src/blob/persistence/LokiReferredExtentsAsyncIterator.ts, src/blob/utils/constants.ts, src/common/IDataStore.ts, src/common/IGCManager.ts, src/common/ServerBase.ts, tests/blob/apis/blockblob.test.ts, tests/blob/blockblob.highlevel.test.ts, tests/blob/specialnaming.test.ts, tsconfig.json
* Added GC manager to cleanup unused persistency extent mapped files 
* Download uncommitted blockblob will return error 
* All delete and override operations is now async powered by GC 
* persistency layer extentID and localfile mapping is now kept in DB 
* Added async iterators to iterator extents from blobdatastore
* otpmized persistency layer comments and naming
=> [NewArch] GC

src/blob/errors/StorageErrorFactory.ts, src/blob/handlers/BlobHandler.ts, src/blob/handlers/ContainerHandler.ts, src/blob/handlers/ServiceHandler.ts, src/blob/persistence/IBlobDataStore.ts, src/blob/utils/constants.ts, src/blob/utils/utils.ts, tests/blob/apis/blob.test.ts, tests/blob/apis/container.test.ts, tests/blob/apis/pageblob.test.ts, tests/blob/apis/service.test.ts
1.  GetContainerACL still not work with signedIdentifiers, so the related case is skip.
2. Some page tier not in Azurite (P15, P60, P70, P80), but in doc https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-types#premium-ssd
=> Add GetAccountInfo, SetBlobTier, Get/Set ContainerACL

src/blob/handlers/BlobHandler.ts, tests/blob/apis/blob.test.ts
=> Fixed GetBlockBlob missing Content-Range header

CONTRIBUTION.md, ChangeLog.md, README.md, azure-pipelines.yml, package-lock.json, package.json, src/blob/utils/constants.ts
* Fixed npm install -g issue in linux and mac; 
* Updated Azure Pipeline validation npm package installation, docker build, and VSC package generation
* Bumped version to 3.1.2-preview as 3.1.1-preview has been taken in npm
=> Bumped version to 3.1.2-preview; 

.vscode/launch.json, lib/actions/table/QueryEntities.js, test/01_Basic_table_Tests.js
=> Fix query entities for single result in a collection

lib/AzuriteTable.js, package-lock.json, package.json
=> Add support for HTTP Method Overrides

package-lock.json, package.json, python/update-multi.py, python/update.py, src/blob/persistence/IBlobMetadataStore.ts, src/blob/persistence/SqlBlobMetadataStore.ts, tests/blob/persistence/SqlBlobMetadataStore.test.ts
=> Onpremise Implemented SqlBlobMetadataStore blockblob upload

src/blob/handlers/BlobHandler.ts, src/blob/handlers/BlockBlobHandler.ts, src/blob/handlers/ContainerHandler.ts, src/blob/handlers/PageBlobHandler.ts, src/blob/handlers/ServiceHandler.ts, src/blob/utils/utils.ts, tests/blob/apis/blob.test.ts, tests/blob/apis/blockblob.test.ts, tests/blob/apis/container.test.ts, tests/blob/apis/pageblob.test.ts, tests/blob/apis/service.test.ts, tests/blob/blockblob.highlevel.test.ts, tests/blob/sas.test.ts
=> Support return Client request ID in Blob request

src/blob/handlers/BlobHandler.ts, src/blob/handlers/BlockBlobHandler.ts, src/blob/handlers/ContainerHandler.ts, src/blob/handlers/PageBlobHandler.ts, src/blob/handlers/ServiceHandler.ts, src/blob/utils/constants.ts, src/blob/utils/utils.ts, src/queue/generated/artifacts/mappers.ts, src/queue/generated/artifacts/models.ts, src/queue/generated/artifacts/parameters.ts, src/queue/handlers/MessageIdHandler.ts, src/queue/handlers/MessagesHandler.ts, src/queue/handlers/QueueHandler.ts, src/queue/handlers/ServiceHandler.ts, swagger/queue-storage.json, tests/blob/apis/blob.test.ts, tests/blob/apis/blockblob.test.ts, tests/blob/apis/container.test.ts, tests/blob/apis/pageblob.test.ts, tests/blob/apis/service.test.ts, tests/blob/blockblob.highlevel.test.ts, tests/blob/sas.test.ts, tests/queue/apis/messageid.test.ts, tests/queue/apis/messages.test.ts, tests/queue/apis/queue.test.ts, tests/queue/apis/queueService.test.ts, tests/queue/queueSas.test.ts
=> Support return Client request ID in queue request

ChangeLog.md
=> Add upcoming release tag in Change log

ChangeLog.md, src/azurite.ts, src/blob/handlers/ServiceHandler.ts, src/blob/persistence/IBlobMetadataStore.ts, src/blob/persistence/LokiBlobMetadataStore.ts, src/blob/persistence/SqlBlobMetadataStore.ts, tests/blob/apis/service.test.ts
Links to issue https://github.com/Azure/Azurite/issues/275
=> List containers should be displayed in sorted order

ChangeLog.md, src/blob/context/blobStorageContext.middleware.ts, src/blob/persistence/LokiBlobMetadataStore.ts, src/blob/persistence/SqlBlobMetadataStore.ts, src/blob/utils/constants.ts, src/common/utils/utils.ts, src/queue/context/queueStorageContext.middleware.ts, src/queue/utils/constants.ts
1. Fix issue: https://github.com/Azure/Azurite/issues/293
2. Add API version validation , validate API version get from https://docs.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions
Don't have test now since:
1. For snapshot, JS test can't repro the issue. The issue is from PSH with XSCL
2. For API version, it's not easy to add test. We have manually test with PSH. Opened a task (P2) to add it later.
Please go to CONTRIBUTION.md for steps about setting up development environment and recommended Visual …
=> Fix get snapshot 404 issue, and add API version validation

src/blob/preflight/PreflightMiddlewareFactory.ts, src/blob/utils/constants.ts, src/queue/QueueRequestListenerFactory.ts, src/queue/preflight/PreflightMiddlewareFactory.ts, src/queue/utils/constants.ts, tests/blob/blobCorsRequest.test.ts, tests/queue/queueCorsRequest.test.ts
Fix these typos:
ACCESS_CONTROL_EXPOSE_HEADER
ACCESS_CONTROL_ALLOW_HEADERS
=> fix CORS typos

ChangeLog.md, src/blob/errors/StorageErrorFactory.ts, src/blob/handlers/BlobHandler.ts, src/blob/handlers/PageBlobHandler.ts, src/blob/persistence/LeaseBreakingState.ts, src/blob/persistence/LeaseBrokenState.ts, src/blob/persistence/LeaseLeasedState.ts, src/blob/persistence/LokiBlobMetadataStore.ts, tests/blob/apis/blob.test.ts
Follow https://github.com/Azure/Azurite/issues/338:
Fix some leased issues found in .net SDK test, include:
- Fix the issue that Copy Blob will overwrite the destination blob Lease status.
- Fix the issue that Change Lease fail when blob lease id only matches the input ProposedLeaseId.
- Fix the issue that UploadPage, ClearPage will fail on leased Page blob, even input correct lease id.
- Change some lease error code to align with server.
Please go to CONTRIBUTION.md for steps about setting up development environment and recommended Visual …
=> Fix some leased issues found in .net SDK test

ChangeLog.md, src/blob/handlers/BlockBlobHandler.ts, src/queue/handlers/MessagesHandler.ts, tests/blob/apis/blockblob.test.ts, tests/queue/apis/messages.test.ts
To fix https://github.com/Azure/Azurite/issues/326, https://github.com/Azure/Azurite/issues/308
=> Filter getBlockList returnValue with BlockListingFilter (#326); Allow max TTL in PutMessage (#308)

tests/blob/apis/blob.test.ts
=> Add test case for accessTierInferred

ChangeLog.md, src/blob/utils/utils.ts
=> Change etag format to align with Azure Server behavior.

lib/model/table/AzuriteTableRequest.js
Was also replacing all @ by single quotes, breaking matches with strings containing @ (i.e. email addresses).
=> Escaped quotation marks replacement fix.

src/blob/BlobRequestListenerFactory.ts, src/blob/authentication/BlobTokenAuthenticator.ts, src/queue/QueueRequestListenerFactory.ts, src/queue/authentication/QueueTokenAuthenticator.ts
A start to resolving #389 
Discussing with Azurite team about taking over the work, and they will add Tests and further implementation.
=> Add Bearer Token Credential support

README.md, package-lock.json
=> Update HTTPS and Storage Explorer instructions.

README.md
Sync commit from dev to master
=> Update HTTPS and Storage Explorer instructions. (#431)

.github/workflows/codeql.yml
=> Add CodeQL security scanning (#450)

README.md
I just noticed that casing was incorrect on one of the class names, so if someone copy and pastes the code it will not work.
=> Fix class casing

src/blob/generated/utils/serializer.ts, src/queue/generated/utils/serializer.ts, src/table/generated/utils/serializer.ts
=> Update serializer log format

.vscode/launch.json, azure-pipelines.yml, src/blob/generated/ExpressResponseAdapter.ts, src/blob/generated/IResponse.ts, src/blob/generated/utils/serializer.ts, src/blob/generated/utils/utils.ts, src/queue/generated/ExpressResponseAdapter.ts, src/queue/generated/IResponse.ts, src/queue/generated/utils/serializer.ts, src/queue/generated/utils/utils.ts, src/table/TableRequestListenerFactory.ts, src/table/context/TableStorageContext.ts, src/table/errors/StorageError.ts, src/table/errors/StorageErrorFactory.ts, src/table/generated/ExpressResponseAdapter.ts, src/table/generated/IResponse.ts, src/table/generated/utils/serializer.ts, src/table/generated/utils/utils.ts, src/table/handlers/ServiceHandler.ts, src/table/handlers/TableHandler.ts, src/table/middleware/tableStorageContext.middleware.ts, src/table/persistence/ITableMetadataStore.ts, src/table/persistence/LokiTableMetadataStore.ts, src/table/utils/constants.ts, tests/table/apis/table.test.ts
Checked every generated Handler interface can be properly dispathced and deserialized.
=> Generated code fix for table

Dockerfile, README.mcr.md, README.md, azure-pipelines.yml
Updated Dockerfile to use Table API. README updates are only for Docker.
https://github.com/Azure/Azurite/issues/510
No test cases have been added.
=> Update Dockerfile for table support.

src/table/errors/StorageErrorFactory.ts, src/table/handlers/TableHandler.ts, src/table/persistence/ITableMetadataStore.ts, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.entity.test.ts, tests/table/apis/table.test.ts, tslint.json
I'm getting a ECONNRESET error when running the entity tests that I have written to test the etag matching error...
I can't explain it. I'll submit the PR now so that you can take a look.  
I'm hoping fresh eyes will spot the error in the morning! :smile:
=> Table delete entity

package.json, src/table/errors/StorageErrorFactory.ts, src/table/generated/handlers/ITableHandler.ts, src/table/handlers/TableHandler.ts, src/table/persistence/ITableMetadataStore.ts, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.entity.test.ts
Added the update Entity feature and tests
=> Add update Entity feature

src/table/TableRequestListenerFactory.ts, src/table/generated/artifacts/specifications.ts
=> modify post verb to merge

src/table/handlers/TableHandler.ts, src/table/persistence/ITableMetadataStore.ts, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.test.ts, tsconfig.json
- Query table implementation & tests
- Added functional test cases to table.test.ts
#484
=> Add table query feature

README.md, src/table/TableRequestListenerFactory.ts, src/table/TableServer.ts, src/table/errors/StorageErrorFactory.ts, src/table/middleware/tableStorageContext.middleware.ts, src/table/utils/constants.ts, src/table/utils/utils.ts, tests/table/apis/table.test.ts
I installed my locally build package globally and tested the command line parameters. I updated the README to note Table specific items. Seems to work for me.
Fixes #511
=> Update readme to include table changes

ChangeLog.md, src/blob/utils/constants.ts, src/queue/utils/constants.ts
This PR is for:
1. Upgrade API version to STG74 2020-02-10
2. Update Change log to include changes after Azurite 3.8.0 release (exclude text update and some dependence upgrade)
Will have another PR for:
1. Upgrade version to 3.9.0
2. upgrade APIversion/ version in Readme
3. Upgrade not supported API in Readme for STG74
=> Upgrade API version to STG74 "2020-02-10", and update changelog for new release

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts
Upgrade to 3.9.0.
Should not merge it to master, until close to release.
=> Upgrade to 3.9.0

Azurite.nuspec, package-lock.json, package.json, release-notes.md
legacy-dev
Updates only for 2.7.3 release
=> Legacy Release 2.7.3

lib/core/table/TableStorageManager.js, test/01_Basic_table_Tests.js
* Added support for table storage $top query option
* Added unit test for using $top query option
=> Add support for table storage $top query option

ChangeLog.md, Dockerfile, PULL_REQUEST_TEMPLATE.md, src/blob/utils/constants.ts, src/queue/utils/constants.ts
=> Upgrade API version to STG75 2020-04-08, and update changelog for new release

ChangeLog.md, src/blob/handlers/BlockBlobHandler.ts, src/blob/handlers/PageBlobHandler.ts, src/blob/persistence/IBlobMetadataStore.ts, src/blob/persistence/LokiBlobMetadataStore.ts, src/blob/persistence/SqlBlobMetadataStore.ts, tests/blob/apis/blockblob.test.ts, tests/blob/apis/pageblob.test.ts
Fix issue https://github.com/Azure/Azurite/issues/636, https://github.com/Azure/Azurite/issues/640
=> Fix getblocklist from snapshot issue (#639), and get/clear/upate with invalid page range issue(#640)

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts
=> Upgrade to 3.10.0

README.mcr.md, README.md
For https://github.com/Azure/Azurite/issues/668, customer can't know this clearly from current doc.
As this is doc change, not code change, should not need change log.
=> Fix readme to add required parameters for docker

ChangeLog.md, src/blob/generated/artifacts/models.ts, src/blob/generated/artifacts/specifications.ts, src/blob/handlers/BlobHandler.ts, swagger/blob-storage-2019-02-02.json, tests/blob/apis/blob.test.ts
Fix part of issue https://github.com/Azure/Azurite/issues/632, that set tier on leased blob, the lease ID will be omit.
=> Fix issue that  lease ID will be omit when set tier on leased blob.

Dockerfile, package.json
This PR enables installation from a github branch directly, for example
npm install git+https://github.com/temporaer/Azurite.git#add-prepare-script
=> add prepare script to facilitate installation from github

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts
=> Upgrade to 3.11.0, Upgrade API version to STG76 2020-06-12

ChangeLog.md, src/table/handlers/TableHandler.ts, tests/table/apis/table.entity.test.ts
Azurite table now allows empty rowkey while inserting an entity.
This PR tackles issue #704 for azurite table storage
=> 704 allow empty rowkey

ChangeLog.md, src/table/entity/EdmDateTime.ts, src/table/errors/StorageErrorFactory.ts, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.entity.test.ts, tests/table/apis/table.test.ts
The PR is to fix issue: 
https://github.com/Azure/Azurite/issues/746 : [Logic Apps] Azurite does not store date time properties in UTC
https://github.com/Azure/Azurite/issues/748 : [Logic Apps] Incorrect error code and message when deleting a table that does not exist
=> Fix issue #746 and #748

package-lock.json, package.json, src/table/batch/TableBatchOrchestrator.ts, tests/table/apis/table.entity.tests.azure.data-tables.ts
Adds Test for @azure/data-tables
Confirms and fixes #738
=> Adds Test for @azure/data-tables & confirms that #738 is resolved

.vscodeignore, NOTICE.txt
=> 3.12.0 table

src/table/errors/StorageErrorFactory.ts
=> Correct Spelling on Storage Error

README.md, package.json, src/common/VSCEnvironment.ts, src/common/VSCServerManagerTable.ts, src/extension.ts
fix issue https://github.com/Azure/Azurite/issues/772.
Added and changed files:
1.package.json
2.src/common/VSCEnvironment.ts
3.src/common/VSCServerManagerTable.ts
4.src/extension.ts
5.README.md
@jongio for notification.
=> Add table service in visual code extension

ChangeLog.md, src/blob/errors/StorageErrorFactory.ts, src/blob/middlewares/blobStorageContext.middleware.ts, src/blob/utils/utils.ts, src/table/errors/StorageErrorFactory.ts, src/table/handlers/TableHandler.ts, src/table/middleware/tableStorageContext.middleware.ts, src/table/utils/utils.ts, tests/blob/apis/container.test.ts
This is to fix issue: https://github.com/Azure/Azurite/issues/456
=> Validate container name and table name

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Upgrade API version to STG77 2020-08-04, and version to 3.13.0

README.md
=> Fix Readme.md by adding table service to V3

ChangeLog.md, README.md, src/blob/middlewares/blobStorageContext.middleware.ts, src/table/middleware/tableStorageContext.middleware.ts, tests/blob/apis/container.test.ts, tests/blob/apis/service.test.ts
To fix issue #824, and update readme.md
=> [Storage] Fix Get Account/Service properties fail, and update readme

src/table/main.ts
Fixing typo in an error message.
=> Fix error message typo

README.md
=> Add sample to user https on docker

package-lock.json
=> Revert "Bump @types/express from 4.17.1 to 4.17.13"

package-lock.json, package.json
Reverts Azure/Azurite#912
The change does not pass CI validation.
=> Revert "Bump @azure/ms-rest-js from 1.11.2 to 2.5.3"

package-lock.json, package.json
=> Revert "Bump @types/node from 14.14.24 to 16.3.1"

ChangeLog.md, src/blob/persistence/LokiBlobMetadataStore.ts, tests/blob/apis/container.test.ts
=> Fix continuation token not work correctly when blob names are only number

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Upgrade API version to 2020-10-02 and version to 3.14.0

ChangeLog.md, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.entity.tests.azure.data-tables.ts
added test case to cover pagination number of results, and the distinct results returned by the query.
Also tested using different numbers of entities.  
Fixes #722
=> fixes #722, query result is now complete using pagination

ChangeLog.md, src/table/handlers/TableHandler.ts, src/table/persistence/ITableMetadataStore.ts, src/table/persistence/LokiTableMetadataStore.ts, tests/table/persistence/LokiTableMetadataStore.test.ts
Fix https://github.com/Azure/Azurite/issues/794
=> Add table name filtering

tests/table/apis/table.entity.tests.azure.data-tables.ts
Test validates issue from #806.
No repro with this test or a C# project.
Closing issue #806
=> added test to cover issue in #806, no repro in C# or with this test

ChangeLog.md, package-lock.json, src/table/handlers/ServiceHandler.ts, src/table/persistence/ITableMetadataStore.ts, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.service.test.properties.ts, tests/table/apis/table.service.test.ts
Adds support for setServiceProperties
=> Table set service properties

ChangeLog.md, src/blob/generated/artifacts/mappers.ts, src/blob/generated/artifacts/models.ts, src/blob/handlers/BlobHandler.ts, swagger/blob-storage-2019-02-02.json, swagger/blob.md, tests/blob/apis/blockblob.test.ts, tests/blob/apis/pageblob.test.ts
Can fix https://github.com/Azure/Azurite/issues/963
=> Fixed Blob_Download API by adding header `x-ms-creation-time` in responds

README.md, src/blob/middlewares/blobStorageContext.middleware.ts, src/common/utils/constants.ts, src/queue/middlewares/queueStorageContext.middleware.ts, src/table/middleware/tableStorageContext.middleware.ts
This pull request improves changes imported by #416, and completes #403.
I have not added any tests yet, since I am not sure how to test the changes well - testing would involve changing hosts file.
Please provide some advice.
Thank you 😃
=> Access storage account with production-style url without special suffix

package-lock.json, package.json, src/queue/QueueRequestListenerFactory.ts, src/table/TableRequestListenerFactory.ts, src/table/errors/StorageErrorFactory.ts, src/table/middleware/PreflightMiddlewareFactory.ts, src/table/utils/constants.ts, tests/queue/RequestPolicy/OPTIONSRequestPolicyFactory.ts, tests/table/RequestPolicy/OPTIONSRequestPolicy.ts, tests/table/RequestPolicy/OriginPolicy.ts, tests/table/apis/table-api-testing.md, tests/table/apis/table.batch.tests.errorhandling.ts, tests/table/apis/table.entity.tests.azure.data-tables.ts, tests/table/tableCorsRequest.test.ts
- Implement preflight table request
- Add test cases for preflight table request
- Update @azure/data-tables to 12.1.1
- Update @azure/core-auth to 1.3.2
- Update @azure/core-rest-pipeline to 1.2.0
- Align table batch tests with the latest data-tables SDK
=> Implement preflight table request and add test cases (resolves #958)

.vscode/launch.json, ChangeLog.md, src/table/handlers/TableHandler.ts, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.batch.tests.errorhandling.ts, tests/table/apis/table.entity.test.utils.ts, tests/table/apis/table.entity.tests.azure.data-tables.ts, tests/table/apis/table.entity.tests.issues.ts
fixes #1003 and updating some tests.
=> Fixes Paged Query Across Partitions

BreakingChanges.md
=> Add breaking change notice for 3.14.2

README.md
https://github.com/Azure/Azurite/issues/1039
https://github.com/Azure/Azurite/issues/716
=> Update readme for DNS name change

ChangeLog.md, src/blob/generated/artifacts/models.ts, src/blob/generated/artifacts/parameters.ts, src/blob/handlers/ContainerHandler.ts, swagger/blob-storage-2019-02-02.json, swagger/blob.md, tests/blob/RequestPolicy/QueryRequestPolicyFactory.ts, tests/blob/apis/container.test.ts
Fix issue:
https://github.com/Azure/Azurite/issues/1053
https://github.com/Azure/Azurite/issues/813
https://github.com/Azure/Azurite/issues/706
product code added. test case will add later.
=> Fix list blob/container include query parameter issues.

ChangeLog.md, src/blob/authentication/BlobSharedKeyAuthenticator.ts, src/queue/authentication/QueueSharedKeyAuthenticator.ts, src/table/authentication/TableSharedKeyAuthenticator.ts, src/table/authentication/TableSharedKeyLiteAuthenticator.ts
To Fix issue: https://github.com/Azure/Azurite/issues/1142
=> Fix the sharedkey validation fail on secondary location with IP style Uri

README.mcr.md
No test cases added. DOC addition.
Added example of how to start Azurite as named Docker service (deamon)
=> Added example of how to start as named deamon.

src/table/entity/EntityProperty.ts, tests/table/apis/AzureDataTablesTestEntity.ts, tests/table/apis/table.entity.tests.azure.data-tables.ts
Adds test cases for double values using Azure Data Tables.
=> Fixes backwards compatability for Azure-Storage SDK double value props

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Upgrade version to 15.0.0, and API version to 2021-02-12

ChangeLog.md, src/table/persistence/LokiTableMetadataStore.ts, tests/table/apis/table.entity.tests.issues.ts
Fix https://github.com/Azure/Azurite/issues/1214
=> Encode next partition key and row key using base64 to avoid Unicode issues

ChangeLog.md, tests/table/sas.test.ts
=> Fix a table sas test failure since sas expire in the past.

ChangeLog.md, src/blob/context/BlobStorageContext.ts, src/blob/generated/Context.ts, src/blob/handlers/BlobHandler.ts, src/blob/middlewares/blobStorageContext.middleware.ts
Fix issue https://github.com/Azure/Azurite/issues/1245
=> Fixed startCopyFromURL and copyFromURL API not respect `--disableProductStyleUrl` in parse source Uri

README.md
The connection string for the https connection is not complete. The table storage is missing.
=> Add table storage to https connection string

ChangeLog.md, src/table/batch/TableBatchOrchestrator.ts, src/table/handlers/TableHandler.ts, tests/table/apis/table.entity.test.ts
Resolve https://github.com/Azure/Azurite/issues/1234.
=> Fix batch handling of empty partition key and empty row key

ChangeLog.md, src/queue/authentication/QueueSASAuthenticator.ts
Fixes issue with class name in #659 
Just getting my feet wet with this project 😄
=> Fix class name of QueueSASAuthenticator

ChangeLog.md, src/table/handlers/TableHandler.ts, tests/table/apis/table.entity.azure.data-tables.test.ts
Fix https://github.com/Azure/Azurite/issues/1467
=> Detect request bodies that are too large on Table batch requests

src/blob/handlers/ContainerHandler.ts, src/blob/persistence/IBlobMetadataStore.ts, src/blob/persistence/LokiBlobMetadataStore.ts, src/blob/persistence/PageWithDelimiter.ts, src/blob/persistence/SqlBlobMetadataStore.ts, tests/blob/apis/container.test.ts, tests/blob/pagewithdelimiter.test.ts
=> Fix list blob next marker when prefixes should be squashed

azure-pipelines.yml, package.json
=> Workaround a build error with prettier-tslint

ChangeLog.md, src/blob/errors/StorageErrorFactory.ts, src/blob/utils/utils.ts, src/queue/errors/StorageErrorFactory.ts, src/queue/utils/utils.ts, src/table/errors/StorageErrorFactory.ts, src/table/utils/utils.ts
Fix the issue https://github.com/Azure/Azurite/issues/1483
=> Fix the error message for invalid API version

ChangeLog.md, src/blob/persistence/LokiBlobMetadataStore.ts, tests/blob/apis/blob.test.ts
Fix issue : https://github.com/Azure/Azurite/issues/1543
=> Fix issue 1543: Copy blobs with if-none-match="*" overwrites target but should return 409

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
Fix issue : https://github.com/Azure/Azurite/issues/1543
=> upgrade version to 3.18.0 and API version to 2021-08-06

ChangeLog.md, README.md
For issue: https://github.com/Azure/Azurite/issues/1568
=> Updated Readme by adding account key must be base64 encoded string

README.md
Took me longer than I'd like to admit to find an example and get Azurite working via Docker Compose, and I'd much rather everyone else not go through the same struggles.
=> Add Docker Compose config example to README.md

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> upgrade version to 3.19.0 and API version to 2021-10-04

.github/workflows/codeql.yml, tests/table/apis/table.validation.rest.test.ts
Fix the recent PR check failure, since codeql failed to validate some test code, however we won't release the test code.
=> Fix codeql failure and update codeql to v2

ChangeLog.md, src/blob/BlobRequestListenerFactory.ts, src/blob/authentication/OperationAccountSASPermission.ts, src/blob/authentication/OperationBlobSASPermission.ts, src/blob/generated/ExpressMiddlewareFactory.ts, src/blob/generated/artifacts/mappers.ts, src/blob/generated/artifacts/models.ts, src/blob/generated/artifacts/operation.ts, src/blob/generated/artifacts/parameters.ts, src/blob/generated/artifacts/specifications.ts, src/blob/generated/handlers/IContainerHandler.ts, src/blob/generated/handlers/handlerMappers.ts, src/blob/handlers/BlobBatchHandler.ts, src/blob/handlers/BlobBatchSubRequest.ts, src/blob/handlers/BlobBatchSubResponse.ts, src/blob/handlers/ContainerHandler.ts, src/blob/handlers/ServiceHandler.ts, src/blob/handlers/SubResponseTextBodyStream.ts, src/blob/middlewares/AuthenticationMiddlewareFactory.ts, src/blob/middlewares/blobStorageContext.middleware.ts, src/blob/utils/constants.ts, swagger/blob-storage-2019-02-02.json, swagger/blob.md, tests/blob/apis/blobbatch.test.ts, tests/blob/blockblob.highlevel.test.ts, tests/blob/oauth.test.ts
Manually tested:
1. subrequest count exceed the limition (> 256)
2. Different operation method in one batch request
3. No id in one of subrequest
Batch request support all of share key/SAS token/AAD token credentials in both of service and container scope batch request.
=> Add support for blob batch

ChangeLog.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Update package version to 3.20.0

ChangeLog.md, src/table/handlers/TableHandler.ts, tests/table/apis/table.entity.test.ts, tests/table/models/AzureDataTablesTestEntity.ts
Fix issue https://github.com/Azure/Azurite/issues/1757
=> Fix issue 1757: make request fail on creating an entity without specifying a property value of type DateTimeOffset

ChangeLog.md, src/blob/authentication/AccountSASAuthenticator.ts, src/blob/authentication/BlobSASAuthenticator.ts, src/blob/authentication/BlobSharedKeyAuthenticator.ts, src/blob/authentication/IBlobSASSignatureValues.ts, src/blob/generated/utils/utils.ts, src/blob/handlers/ServiceHandler.ts, src/blob/utils/constants.ts, src/blob/utils/utils.ts, tests/blob/apis/service.test.ts, tests/blob/oauth.test.ts, tests/queue/oauth.test.ts, tests/table/auth/oauth.test.ts, tests/table/utils/table.entity.tests.rest.submitter.ts, tests/testutils.ts
=> Add support for user delegation key

NOTICE.txt
=> Update Notice file for dependency change of PR 1764

README.md
=> remove supported feature from not supported feature list

ChangeLog.md, src/table/persistence/QueryTranscriber/StatePredicateFinished.ts, tests/table/apis/table.entity.query.test.ts
Fix issue: https://github.com/Azure/Azurite/issues/1787
=> fix 1787: table query with true/false failure

ChangeLog.md, src/table/persistence/QueryTranscriber/StateQueryFinished.ts
=> Fix issue when querying table entity whose properties includes a special char

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Bump package verion to 3.22.0, Bump service API version to 2021-12-02

ChangeLog.md, src/queue/authentication/QueueSASAuthenticator.ts, tests/queue/queueSas.test.ts
Fix this issue:
https://github.com/Azure/Azurite/issues/1811
=> Fix issue 1811: queue service sas without Start time fail request

ChangeLog.md, src/blob/authentication/AccountSASAuthenticator.ts, src/blob/authentication/BlobSASAuthenticator.ts, src/blob/authentication/BlobSharedKeyAuthenticator.ts, src/blob/authentication/BlobTokenAuthenticator.ts, src/blob/errors/StorageErrorFactory.ts, src/queue/authentication/AccountSASAuthenticator.ts, src/queue/authentication/QueueSASAuthenticator.ts, src/queue/authentication/QueueSharedKeyAuthenticator.ts, src/queue/authentication/QueueTokenAuthenticator.ts, src/queue/errors/StorageErrorFactory.ts, src/table/authentication/AccountSASAuthenticator.ts, src/table/authentication/TableSASAuthenticator.ts, src/table/authentication/TableSharedKeyAuthenticator.ts, src/table/authentication/TableSharedKeyLiteAuthenticator.ts, src/table/authentication/TableTokenAuthenticator.ts, tests/blob/oauth.test.ts, tests/queue/oauth.test.ts, tests/table/auth/oauth.test.ts
To Fix https://github.com/Azure/Azurite/issues/1816
=> Change error code to 404 when account not exist

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
Upgrade API version to 2022-11-02
Bump package version to 3.23.0
=> Upgrade API version to 2022-11-02

ChangeLog.md, src/blob/handlers/BlobBatchHandler.ts
Fix issue of batch blob request from cpp SDK doesn't work: 1822
=> Fix issue of batch blob request from cpp SDK doesn't work: 1822

package-lock.json, package.json, src/blob/handlers/ServiceHandler.ts, src/queue/handlers/MessageIdHandler.ts, src/queue/handlers/MessagesHandler.ts, src/queue/handlers/ServiceHandler.ts, src/table/handlers/ServiceHandler.ts
From PR https://github.com/Azure/Azurite/pull/1906
Since the PR will fail on check, add fixing code and raise a new PR.
This is also to fix issue: https://github.com/Azure/Azurite/issues/1907
=> Bump xml2js from 0.4.23 to 0.5.0

ChangeLog.md, src/blob/errors/StorageErrorFactory.ts, src/blob/handlers/BlobHandler.ts, tests/blob/apis/blob.test.ts
To Fix https://github.com/Azure/Azurite/issues/532
=> Fixed #532: setMetadata API allows invalid metadata name with hyphen.

package-lock.json, package.json, src/blob/persistence/SqlBlobMetadataStore.ts
=> Upgrade sequelize to 6.31.0

ChangeLog.md, src/blob/authentication/OperationAccountSASPermission.ts, src/blob/authentication/OperationBlobSASPermission.ts, src/blob/errors/StorageErrorFactory.ts, src/blob/handlers/AppendBlobHandler.ts, src/blob/handlers/BlobHandler.ts, src/blob/handlers/BlockBlobHandler.ts, src/blob/handlers/ContainerHandler.ts, src/blob/handlers/PageBlobHandler.ts, src/blob/persistence/IBlobMetadataStore.ts, src/blob/persistence/LokiBlobMetadataStore.ts, src/blob/persistence/SqlBlobMetadataStore.ts, src/blob/utils/utils.ts, src/common/persistence/SqlExtentMetadataStore.ts, tests/blob/apis/blob.test.ts
This is a PR for Blob tag Phase I change:
Implement set/get BlobTag on API: GetBlobTag, SetBlobTag, GetBlob, GetBlobProperties, PUTBlob (Block/page/append), ListBlob, PutBlockList, copyFromURL, startCopyFromURL.
https://github.com/Azure/Azurite/issues/1871
https://github.com/Azure/Azurite/issues/1872
=> [Blob Tag] Phase I - Implement SetTag, GetTag on differenet blob APIs

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
Update service version to 2023-01-03 
Update package version to 3.24.0
=> Update service version to 2023-01-03 

ChangeLog.md, src/table/persistence/LokiTableStoreQueryGenerator.ts, tests/table/apis/table.entity.query.test.ts
Fix issue https://github.com/Azure/Azurite/issues/1880 
=> Fix query table fail with filter condition as string.Empty

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Bump service version to 2023-08-03

package-lock.json, package.json
…2128)"
This reverts commit 3a30cb2f6b755cd3f1b1317b6fe43212d9776a7d.
=> Fix build failure caused by PR https://github.com/Azure/Azurite/pull/2128

ChangeLog.md, README.md, src/blob/generated/artifacts/models.ts, src/blob/handlers/BlockBlobHandler.ts, src/blob/persistence/LokiBlobMetadataStore.ts, src/blob/persistence/SqlBlobMetadataStore.ts, swagger/blob-storage-2021-10-04.json, swagger/blob.md, swagger/queue-storage.json, tests/blob/apis/blob.test.ts
For https://github.com/Azure/Azurite/issues/1914
=> Support blob tier Cold

ChangeLog.md, src/blob/handlers/BlockBlobHandler.ts, tests/blob/apis/blob.test.ts
Fix https://github.com/Azure/Azurite/issues/2038
=> Set accessTierInferred to false after upload blob with accessTier (issue #2038)

ChangeLog.md, src/queue/generated/artifacts/mappers.ts, src/queue/generated/artifacts/models.ts, src/queue/handlers/QueueHandler.ts, swagger/queue-storage.json, swagger/queue.md, tests/queue/apis/queue.test.ts
Fix https://github.com/Azure/Azurite/issues/2065
=> Fixed set Queue ACL failure when Start is missing (issue #2065)

ChangeLog.md, src/blob/errors/StorageErrorFactory.ts, src/blob/handlers/BlobHandler.ts, src/blob/handlers/BlockBlobHandler.ts, tests/blob/apis/blob.test.ts
Fix: 
https://github.com/Azure/Azurite/issues/1954
https://github.com/Azure/Azurite/issues/1955
=> Fix issue 1954 & issue 1955

ChangeLog.md, src/blob/BlobRequestListenerFactory.ts, src/blob/handlers/BlobBatchHandler.ts, src/blob/handlers/ContainerHandler.ts, src/blob/handlers/ServiceHandler.ts, tests/blob/apis/blobbatch.test.ts
=> Fix issue of blob batch operations failed on domain style endpoint

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Bump REST API version to 2023-11-03, package version to 3.27.0

ChangeLog.md, src/blob/authentication/BlobSASPermissions.ts, src/blob/authentication/ContainerSASPermissions.ts, src/blob/authentication/OperationAccountSASPermission.ts, src/blob/authentication/OperationBlobSASPermission.ts, src/common/authentication/AccountSASPermissions.ts, src/common/authentication/AccountSASResourceTypes.ts, tests/blob/oauth.test.ts, tests/blob/sas.test.ts
=> Fixed issue of not requiring SAS permission for some specific operations

README.md
Update sample command for PFX certificate use.
=> Fix sample command for PFX cert/pwd

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Bump sevice API version to 2024-02-04 and package version to 3.29.0

ChangeLog.md, src/blob/persistence/LokiBlobMetadataStore.ts, src/blob/persistence/SqlBlobMetadataStore.ts, tests/blob/apis/blob.test.ts
Fix issue https://github.com/Azure/Azurite/issues/2327
=> Fix issue 2327: set tag should not change etag, LMT

ChangeLog.md, src/blob/handlers/ServiceHandler.ts, src/queue/handlers/ServiceHandler.ts, tests/blob/apis/service.test.ts
=> Fixed issue of list container contains metadata even request doesn't have include=metadata (issue #2382)

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Bump API version to 2024-05-04 and package version to 3.30.0

ChangeLog.md, src/blob/errors/StorageErrorFactory.ts, src/blob/handlers/BlobHandler.ts, src/blob/persistence/LokiBlobMetadataStore.ts, tests/blob/apis/blob.test.ts
=> support x-ms-copy-source-tag-option in copy blob (issue #2398)

ChangeLog.md, src/blob/handlers/ServiceHandler.ts, tests/blob/apis/service.test.ts
Fix issue: https://github.com/Azure/Azurite/issues/2416
=> Fix issue 2416: list container without include=metadata should not clear metadata on server.

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Bump REST API version to 2024-11-04

ChangeLog.md, src/blob/handlers/ContainerHandler.ts, tests/blob/apis/container.test.ts
Closes #1730
Only include metadata when requested on blob list endpoints.
=> Only include metadata when requested

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Added support for REST API version 2025-01-05, bump package version

ChangeLog.md, Dockerfile
=> Update node and alpine version

src/common/Telemetry.ts
=> update the telemetry connection string

ChangeLog.md, README.md, package-lock.json, package.json, src/blob/utils/constants.ts, src/queue/utils/constants.ts, src/table/utils/constants.ts
=> Bump API version and package version

ChangeLog.md
=> Fixed change log

ChangeLog.md
=> Fix typo in changelog
